"""Find likely English-Spanish cognate-style matches in a word-list CSV.

This program reads a semicolon-delimited CSV file line by line and prints every
original line whose English entry and Spanish entry are similar enough after a
configurable normalization step.

The script is intended to work for adjective lists, noun lists, adverb lists,
verb lists, and mixed vocabulary lists. It is not tied to adjectives. The only
real requirement is that the input file follows the same basic shape used by the
flashcard CSVs in this repository:

1. The file is semicolon-delimited.
2. Column 1 contains the English text.
3. Column 2 contains the Spanish text.
4. The line may optionally contain additional columns, but only the first two
   columns are used for matching.
5. The line is printed back exactly as it originally appeared if it matches.

How the script decides whether a line matches:

1. The English field is split on commas, so an entry like
   ``"good, nice"`` is treated as two separate English candidates:
   ``good`` and ``nice``.
2. Anything inside parentheses is treated as a note, not a word variation.
   For example, ``light (weight)`` is compared as ``light``.
3. Both English and Spanish are normalized according to the user-editable
   options near the top of the file.
4. The ordered equivalence rules in ``ACTIVE_EQUIVALENCE_RULES`` are tried as
    optional alternatives. The original normalized form is kept, and additional
    normalized variants are generated by selectively applying matching rules.
    This lets you declare patterns that should be treated as equivalent, such as
    ``tion -> cion``, prefix rules such as ``^sci -> ci``, or suffix rules such
    as ``ic$ -> ico``, without forcing every rule to rewrite the word.
5. If enabled, repeated consecutive letters are collapsed. For example,
   ``illogical`` becomes ``ilogical``.
6. The script compares every generated English variant against every generated
    Spanish variant using a strict start-aligned comparison. Matching stops at
    the first mismatch. This means the script counts a matching prefix, not a
    general subsequence.
7. The number of matching prefix letters is divided by the longer normalized
   length of the two words.
8. If the best English candidate for that line meets or exceeds
    ``MATCH_THRESHOLD``, the match is saved for later output.
9. After all matches have been found, the saved matches are sorted before
    printing.

Example:

- English candidate: ``illogical``
- Spanish word: ``ilógico``
- After normalization: ``ilogical`` vs ``ilogico``
- Matching prefix: ``ilogic`` -> 6 letters
- Longer normalized length: 8
- Score: ``6 / 8 = 0.75``

Output behavior:

- The script first collects all matching lines, then sorts them, then prints
    them.
- By default, the script prints only the original matching CSV lines.
- If ``PRINT_MATCH_SCORE`` is enabled, it appends the best match percentage.
- If ``PRINT_USED_RULES`` is enabled, it appends which active equivalence rules
    were used for the winning English and Spanish variants.
- If ``PRINT_DOUBLE_LETTER_INFO`` is enabled, it appends whether double-letter
  collapsing changed the winning English candidate or the Spanish word.
- The sorted output order is:
    1. higher match percentage first
    2. among equal percentages, matches with no rules and no double-letter
         collapse first
    3. then matches where no rules were used but double-letter collapse was used
    4. then matches where exactly one rule was used
    5. then matches where two or more rules were used
    6. if items are still tied after that, original file order is used as the
         final tie-breaker

Important limitation:

- This script is generic with respect to word type, but not with respect to
  file structure. It assumes the first two columns are English and Spanish.
  If another list uses a different layout, delimiter, or language order, the
  script would need a small adjustment.
- The rule system now supports three kinds of patterns:
    - plain substring rules such as ``tion -> cion``
    - prefix-only rules written as ``^pattern``
    - suffix-only rules written as ``pattern$``
- The clearly morphological rules in this file were narrowed to prefix-only or
    suffix-only forms where appropriate so they do not fire in unrelated parts of
    a word. A few broad letter-substitution rules still remain intentionally
    broad because they are being used as loose phonetic alternatives.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
import unicodedata
from pathlib import Path
from typing import TypedDict


DEFAULT_INPUT_FILE = Path(
    "/Volumes/Squallywag/Python/Current Python Projects/streamlit_eng_sp_flashcards/csv/PoS_adj_HUGE.csv"
)

MATCH_THRESHOLD = 0.60
PRINT_MATCH_SCORE = False
PRINT_USED_RULES = False
PRINT_DOUBLE_LETTER_INFO = False

NORMALIZATION_OPTIONS = {
    "lowercase": True,
    "remove_parenthetical_notes": True,
    "remove_accents": True,
    "keep_enye": True,
    "keep_letters_only": True,
    "collapse_double_letters": True,
}

# The rules are tried in order as optional alternatives, so keep more specific
# patterns above broader ones. A rule starting with "^" is prefix-only. A rule
# ending in "$" is suffix-only.
ACTIVE_EQUIVALENCE_RULES = [
    ("english", "tion", "cion"),
    ("english", "^sci", "ci"),
    ("english", "^phy", "fi"),
    ("english", "^ph", "f"),
    ("english", "^thi", "ti"),
    ("english", "^th", "t"),
    ("english", "y", "i"),
    ("english", "ck", "c"),
    ("english", "qu", "cu"),
    ("english", "x", "s"),
    ("english", "cian$", "ciano"),
    ("english", "ical$", "ico"),
    ("english", "ic$", "ico"),
    ("english", "ity$", "idad"),
    ("english", "ous$", "oso"),
    ("english", "ary$", "ario"),
    ("english", "ory$", "orio"),
    ("english", "ent$", "ente"),
    ("english", "ant$", "ante"),
    ("english", "ism$", "ismo"),
    ("english", "ist$", "ista"),
    ("english", "ive$", "ivo"),
    ("english", "ance$", "ancia"),
    ("english", "ence$", "encia"),
    ("english", "ure$", "ura"),
    ("english", "z", "s"),
    ("english", "v", "b"),
    ("english", "ce", "se"),
    ("english", "ci", "si"),
    ("english", "gue$", "ge"),
    ("english", "gui", "gi"),
    ("english", "h", ""),
    ("spanish", "ñ", "n"),
]

PARENTHETICAL_NOTES_RE = re.compile(r"\([^)]*\)")
NON_LETTERS_RE = re.compile(r"[^a-zñ]+")
DOUBLE_LETTERS_RE = re.compile(r"(.)\1+")


class MatchDetails(TypedDict):
    candidate: str
    score: float
    prefix_length: int
    normalized_english: str
    normalized_spanish: str
    english_rules: list[tuple[str, str, str]]
    spanish_rules: list[tuple[str, str, str]]
    english_collapsed: bool
    spanish_collapsed: bool


class NormalizedVariant(TypedDict):
    text: str
    used_rules: list[tuple[str, str, str]]
    collapsed_double_letters: bool


class MatchRecord(TypedDict):
    raw_line: str
    score: float
    details: MatchDetails
    original_index: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Print semicolon-delimited CSV lines whose English and Spanish words "
            "are similar enough after normalization."
        )
    )
    parser.add_argument(
        "input_file",
        nargs="?",
        default=str(DEFAULT_INPUT_FILE),
        help="Path to a semicolon-delimited CSV whose first two columns are English and Spanish.",
    )
    return parser.parse_args()


def strip_accents(text: str) -> str:
    if NORMALIZATION_OPTIONS["keep_enye"]:
        text = text.replace("ñ", "__enye_lower__").replace("Ñ", "__enye_upper__")

    normalized = unicodedata.normalize("NFD", text)
    without_marks = "".join(char for char in normalized if unicodedata.category(char) != "Mn")

    if NORMALIZATION_OPTIONS["keep_enye"]:
        without_marks = without_marks.replace("__enye_lower__", "ñ").replace("__enye_upper__", "Ñ")

    return without_marks


def apply_rule(text: str, old: str, new: str) -> str:
    if old.startswith("^"):
        prefix = old[1:]
        if prefix and text.startswith(prefix):
            return f"{new}{text[len(prefix):]}"
        return text

    if old.endswith("$"):
        suffix = old[:-1]
        if suffix and text.endswith(suffix):
            return f"{text[:-len(suffix)]}{new}"
        return text

    return text.replace(old, new)


def generate_rule_variants(text: str, language: str) -> list[tuple[str, list[tuple[str, str, str]]]]:
    variants: dict[str, list[tuple[str, str, str]]] = {text: []}

    for rule_language, old, new in ACTIVE_EQUIVALENCE_RULES:
        if rule_language != language:
            continue

        expanded = dict(variants)
        for variant_text, used_rules in variants.items():
            replaced = apply_rule(variant_text, old, new)
            if replaced != variant_text and replaced not in expanded:
                expanded[replaced] = used_rules + [(rule_language, old, new)]
        variants = expanded

    return [(variant_text, used_rules) for variant_text, used_rules in variants.items()]


def collapse_double_letters(text: str) -> str:
    return DOUBLE_LETTERS_RE.sub(r"\1", text)


def normalize_text(text: str, language: str) -> str:
    variants = normalize_text_with_details(text, language)
    return variants[0]["text"] if variants else ""


def normalize_text_with_details(text: str, language: str) -> list[NormalizedVariant]:
    normalized = text

    if NORMALIZATION_OPTIONS["lowercase"]:
        normalized = normalized.lower()

    if NORMALIZATION_OPTIONS["remove_parenthetical_notes"]:
        normalized = PARENTHETICAL_NOTES_RE.sub("", normalized)

    if NORMALIZATION_OPTIONS["remove_accents"]:
        normalized = strip_accents(normalized)

    variants: dict[str, NormalizedVariant] = {}
    for variant_text, used_rules in generate_rule_variants(normalized, language):
        cleaned_text = variant_text

        if NORMALIZATION_OPTIONS["keep_letters_only"]:
            cleaned_text = NON_LETTERS_RE.sub("", cleaned_text)

        collapsed_double_letters = False
        if NORMALIZATION_OPTIONS["collapse_double_letters"]:
            collapsed = collapse_double_letters(cleaned_text)
            collapsed_double_letters = collapsed != cleaned_text
            cleaned_text = collapsed

        if cleaned_text not in variants:
            variants[cleaned_text] = {
                "text": cleaned_text,
                "used_rules": used_rules,
                "collapsed_double_letters": collapsed_double_letters,
            }

    return list(variants.values())


def split_english_candidates(english_text: str) -> list[str]:
    cleaned = english_text
    if NORMALIZATION_OPTIONS["remove_parenthetical_notes"]:
        cleaned = PARENTHETICAL_NOTES_RE.sub("", cleaned)
    return [part.strip() for part in cleaned.split(",") if part.strip()]


def matching_prefix_length(left: str, right: str) -> int:
    matches = 0
    for left_char, right_char in zip(left, right):
        if left_char != right_char:
            break
        matches += 1
    return matches


def similarity_score(english_text: str, spanish_text: str) -> float:
    return float(match_details(english_text, spanish_text)["score"])


def match_details(english_text: str, spanish_text: str) -> MatchDetails:
    best_details: MatchDetails = {
        "candidate": english_text,
        "score": 0.0,
        "prefix_length": 0,
        "normalized_english": "",
        "normalized_spanish": "",
        "english_rules": [],
        "spanish_rules": [],
        "english_collapsed": False,
        "spanish_collapsed": False,
    }

    english_variants = normalize_text_with_details(english_text, "english")
    spanish_variants = normalize_text_with_details(spanish_text, "spanish")

    for english_variant in english_variants:
        for spanish_variant in spanish_variants:
            normalized_english = english_variant["text"]
            normalized_spanish = spanish_variant["text"]
            longer_length = max(len(normalized_english), len(normalized_spanish))

            if longer_length == 0:
                prefix_length = 0
                score = 0.0
            else:
                prefix_length = matching_prefix_length(normalized_english, normalized_spanish)
                score = prefix_length / longer_length

            if score > best_details["score"]:
                best_details = {
                    "candidate": english_text,
                    "score": score,
                    "prefix_length": prefix_length,
                    "normalized_english": normalized_english,
                    "normalized_spanish": normalized_spanish,
                    "english_rules": english_variant["used_rules"],
                    "spanish_rules": spanish_variant["used_rules"],
                    "english_collapsed": english_variant["collapsed_double_letters"],
                    "spanish_collapsed": spanish_variant["collapsed_double_letters"],
                }

    return best_details


def best_line_match_details(english_text: str, spanish_text: str) -> MatchDetails:
    best_details: MatchDetails = {
        "candidate": "",
        "score": 0.0,
        "prefix_length": 0,
        "normalized_english": "",
        "normalized_spanish": "",
        "english_rules": [],
        "spanish_rules": [],
        "english_collapsed": False,
        "spanish_collapsed": False,
    }

    for candidate in split_english_candidates(english_text):
        details = match_details(candidate, spanish_text)
        if details["score"] > best_details["score"]:
            best_details = details

    return best_details


def best_line_score(english_text: str, spanish_text: str) -> float:
    return float(best_line_match_details(english_text, spanish_text)["score"])


def line_matches(english_text: str, spanish_text: str) -> bool:
    return best_line_score(english_text, spanish_text) >= MATCH_THRESHOLD


def format_used_rules(details: MatchDetails) -> str:
    rules: list[str] = []
    for language, old, new in details["english_rules"]:
        rules.append(f"{language}:{old}->{new}")
    for language, old, new in details["spanish_rules"]:
        rules.append(f"{language}:{old}->{new}")
    if not rules:
        return "rules: none"
    return f"rules: {', '.join(rules)}"


def format_double_letter_info(details: MatchDetails) -> str:
    english_status = "yes" if details["english_collapsed"] else "no"
    spanish_status = "yes" if details["spanish_collapsed"] else "no"
    return f"double_letters: english={english_status}, spanish={spanish_status}"


def match_sort_category(details: MatchDetails) -> int:
    rule_count = len(details["english_rules"]) + len(details["spanish_rules"])
    used_double_letters = details["english_collapsed"] or details["spanish_collapsed"]

    if rule_count == 0 and not used_double_letters:
        return 0
    if rule_count == 0 and used_double_letters:
        return 1
    if rule_count == 1:
        return 2
    return 3


def sort_match_records(matches: list[MatchRecord]) -> list[MatchRecord]:
    return sorted(
        matches,
        key=lambda match: (
            -match["score"],
            match_sort_category(match["details"]),
            match["original_index"],
        ),
    )


def parse_csv_row(raw_line: str) -> list[str] | None:
    if not raw_line.strip():
        return None

    reader = csv.reader([raw_line], delimiter=";", quotechar='"')
    row = next(reader, None)
    if row is None or len(row) < 2:
        return None
    return row


def print_matching_lines(input_file: Path) -> None:
    matches: list[MatchRecord] = []
    with input_file.open("r", encoding="utf-8", newline="") as handle:
        for original_index, raw_line in enumerate(handle):
            row = parse_csv_row(raw_line)
            if row is None:
                continue

            english_text, spanish_text = row[0], row[1]
            details = best_line_match_details(english_text, spanish_text)
            score = float(details["score"])
            if score >= MATCH_THRESHOLD:
                matches.append(
                    {
                        "raw_line": raw_line,
                        "score": score,
                        "details": details,
                        "original_index": original_index,
                    }
                )

    for match in sort_match_records(matches):
        suffix_parts: list[str] = []
        if PRINT_MATCH_SCORE:
            suffix_parts.append(f"{match['score']:.0%}")
        if PRINT_USED_RULES:
            suffix_parts.append(format_used_rules(match["details"]))
        if PRINT_DOUBLE_LETTER_INFO:
            suffix_parts.append(format_double_letter_info(match["details"]))

        if suffix_parts:
            print(f"{match['raw_line'].rstrip()}  [{' | '.join(suffix_parts)}]")
        else:
            print(match["raw_line"], end="")

    print(f"Total matches: {len(matches)}")


def main() -> int:
    args = parse_args()
    input_file = Path(args.input_file)

    if not input_file.exists():
        print(f"File not found: {input_file}", file=sys.stderr)
        return 1

    print_matching_lines(input_file)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())